class Color:
    RED = 'red'
    GREEN = 'green'
    BLUE = 'blue'
    BLACK = 'black'
    WHITE = 'white'
    CYAN = 'cyan'
    YELLOW = 'yellow'
    MAGENTA = 'magenta'
    SILVER = 'silver'
    GRAY = 'gray'
    DARK_GREEN = 'dark green'